version: "3.9"
services:
  reddit1:
    build: .
    container_name: reddit1
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: reddit1
      SUBREDDITS_CONFIG_PATH: config/reddit1.subreddits.yml
    command: ["python","-m","services.reddit1.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  reddit2:
    build: .
    container_name: reddit2
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: reddit2
      SUBREDDITS_CONFIG_PATH: config/reddit2.subreddits.yml
    command: ["python","-m","services.reddit2.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  stocktwits:
    build: .
    container_name: stocktwits
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: stocktwits
    command: ["python","-m","services.stocktwits.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  fourchan:
    build: .
    container_name: fourchan
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: fourchan
      FOURCHAN_BOARDS: ${FOURCHAN_BOARDS}
    command: ["python","-m","services.fourchan.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

