version: "3.9"
services:
  reddit1:
    build: .
    container_name: reddit1
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: reddit1
      SUBREDDITS_CONFIG_PATH: config/reddit1.subreddits.yml
    command: ["python","-m","services.reddit1.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  reddit2:
    build: .
    container_name: reddit2
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: reddit2
      SUBREDDITS_CONFIG_PATH: config/reddit2.subreddits.yml
    command: ["python","-m","services.reddit2.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  reddit_crypto:
    build: .
    container_name: reddit_crypto
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: reddit_crypto
      SUBREDDITS_CONFIG_PATH: config/reddit_crypto.subreddits.yml
    command: ["python","-m","services.reddit_crypto.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  stocktwits:
    build: .
    container_name: stocktwits
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: stocktwits
    command: ["python","-m","services.stocktwits.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  fourchan:
    build: .
    container_name: fourchan
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: fourchan
    command: ["python","-m","services.fourchan.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  fourchan_crypto:
    build: .
    container_name: fourchan_crypto
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: fourchan_crypto
      FOURCHAN_BOARDS: biz
    command: ["python","-m","services.fourchan_crypto.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  signals_worker:
    build: .
    container_name: signals_worker
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: signals_worker
    command: ["python", "-m", "services.signals_worker.main"]

  signals_worker_24h_stock:
    build: .
    container_name: signals_worker_24h_stock
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: signals_worker_24h_stock
      UNIVERSE: stock
    command: ["python", "-m", "services.signals_worker_24h.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

  signals_worker_24h_crypto:
    build: .
    container_name: signals_worker_24h_crypto
    restart: always
    env_file: anthill.env
    environment:
      SERVICE_NAME: signals_worker_24h_crypto
      UNIVERSE: crypto
    command: ["python", "-m", "services.signals_worker_24h.main"]
    healthcheck:
      test: ["CMD","python","-c","import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3

